### PR TITLE
Add shadcn/ui <DialogDrawer> component; move InviteUsersToMatrix into a <Dialog>

### PR DESCRIPTION
**Pull request by fnwbr**
Requires https://github.com/medienhaus/medienhaus-spaces/pull/132

---

## Preview

 image

### CODE REVIEW

**Comment by andirueckel** [comment]
@fnwbr We would like to use the dialog/drawer for all of the actions in `/explore`, too.

Over in https://github.com/medienhaus/medienhaus-spaces/pull/144, @aofn only implemented the dialog component, yet.

Looking at the screenshots above, the following comes to my mind: Regarding our own service table component, it would probably make sense to switch to the shadcn/ui data table component; let’s keep that in mind before making further add-ons/changes/customisations to our own service table component.

**Comment by andirueckel** [comment]
@fnwbr How would we carry over the invite users, dialog, and drawer related changes into `explore-menu-revamp` (or `explore`, if we’d merge `explore-menu-revamp`)? Then I could continue to work on the explore actions/settings, and we would not diverge even more regarding the invite users component.

**Comment by fnwbr** [comment]
```
git checkout explore(-menu-revamp)
git merge invite-users-modal
```

Then use the `DialogDrawer` component like I did here: https://github.com/medienhaus/medienhaus-spaces/pull/143/files#diff-b545937c5147b0e0fd24d3483aaff8cc122d976f17a5856989385dc5b3ba39f1R100-R108

**Comment by andirueckel** [comment]
> ```
> git checkout explore(-menu-revamp)
> git merge invite-users-modal
> ```

I was not able to successfully merge your additions this way; I tried to resolve all conflicts, but I’m running into several build errors now. Maybe to many changes and removals that are still being used in `explore(-menu-revamp)`. Also it seems that `shadecn` still needs to be merged into `explore(-menu-revamp)` as, for example, some files in `pages/etherpad/actions/` are not present in `/explore`?

I’m not quite sure what’s the plan regarding these specific merges, but maybe I shouldn’t touch anything related to dialog and the invite users actions/modal for now until some merges have happened.

**Comment by andirueckel** [comment]
@fnwbr I tend to not want to use the `×` close icon in the dialog top right corner _at all_, and rather always show a close button at the bottom of the dialog, and/or respectively our cancel-confirm/previous-next dual button component.

The current drawer implementation here in `invite-users-modal`, and over in `explore-menu-revamp` seems to always/automatically render a drawer footer with cancel button. https://github.com/medienhaus/medienhaus-spaces/pull/143/files#diff-bb28e57c89d03ac6a22d87dd961d0a5361b2eef87c57a6a14f92c86b6e0a4d4bR28-R32

| Dialog on wide screens | Drawer on narrow screens |
|-|-|
| Screenshot 2024-02-16 at 10 06 54 | Screenshot 2024-02-16 at 10 06 56 |

Let’s keep this in mind, and soon discuss if we want to implement these changes.

**Pull request merged**
